//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerce1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cart_()
        {
            this.cartitems = new HashSet<cartitem>();
        }
    
        public int CartID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual User_ User_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cartitem> cartitems { get; set; }
    }
}
