//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_commerce1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cartitem
    {
        public int CartItemID { get; set; }
        public Nullable<int> CartID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Quantity { get; set; }
    
        public virtual cart_ cart_ { get; set; }
        public virtual product product { get; set; }
    }
}
